### ISSUE TITLE
Is div_par_diffusion calculated correctly?

### ISSUE THREAD

**Issue by bshanahan** [boutproject/hermes#3]
Sorry not sure if this is an issue, but Div_par_diffusion seems to only calculate fluxes at the upper boundary:

https://github.com/boutproject/hermes/blob/master/div_ops.cxx#L529

What about the lower boundary?

I'm curious because I'm trying to use this operator elsewhere and it's causing some issues.

**Comment by bendudson** [comment]
This operator assumes that the mesh is structured in the parallel (y) direction, which is the case here. It loops over all the cell upper boundaries, calculates the flux across that boundary, and then adds the flux to one cell whilst subtracting it from the other. To handle the lower boundary the loop starts from ystart-1 (https://github.com/boutproject/hermes/blob/master/div_ops.cxx#L534). 

I don't think this same operator will work in a more general FCI type method, since there it's not straightforward to add and subtract fluxes in this way. I think you have to separately calculate the fluxes at the upper and lower boundary of each cell in that case.
